training:
  batch_normalization: true
  batch_size: 32
  dropout_rate: 0.5
  embedding_dim: 128
  epochs: 1
  gradient_cliping: true
  learning_rate: 0.8
  maxlen: 128
  model_name: textcnn
  optimizer: sgd
preprocessing:
  classes:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  input_convertor: nn_vectorization
  input_id_column: id
  input_testset: ./data/test.csv
  input_text_column: comment_text
  input_trainset: ./data/train.csv
  random_seed: 0
  split_ratio: 0.3
  maxlen: 128
predict:
  output_path: ./data/submission.csv
